POST http://localhost:8080/api/sale
content-type: application/json
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDM0NTNkYjQ3ZjllNjc5MWQxM2JkNjAiLCJuYW1lIjoiRmFuaXNjYSIsImlhdCI6MTY4MTk0MDAyMX0.365gnemRtqfIMpfHL-CC9RId8xlwHgmRmNwz5StRY9U

{
    "products": [
        {
            "productId": "6434567647f9e6791d13bd7a",
            "quantity": "1"
        }
    ]
}

###
POST https://boss-control-one.vercel.app/api/sale
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDM0NTNkYjQ3ZjllNjc5MWQxM2JkNjAiLCJuYW1lIjoiRmFuaXNjYSIsImlhdCI6MTY4MTk0MDAyMX0.365gnemRtqfIMpfHL-CC9RId8xlwHgmRmNwz5StRY9U

{
    "products": [
        {
            "productId": "642e397f611c3a49bf96cffc",
            "quantity": "1"
        },
        {
            "productId": "642e40334e0922548e935292",
            "quantity": "1"
        }
    ]
}